# Generated by Django 4.0.3 on 2022-03-01 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('pname', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=100)),
                ('s_decr', models.TextField()),
                ('l_descr', models.TextField()),
                ('quantity', models.CharField(max_length=100)),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom3.categories')),
            ],
        ),
        migrations.CreateModel(
            name='product_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='product_image/imgs/')),
                ('active', models.BooleanField(default=True)),
                ('single_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom3.product')),
            ],
        ),
    ]
