# Generated by Django 4.0.3 on 2022-04-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom3', '0002_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='payu',
            fields=[
                ('Cardnum', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Cvv', models.CharField(max_length=3)),
                ('money', models.CharField(max_length=5)),
            ],
        ),
    ]
